version: "3.3"
services:
  docker-host:
    image: qoomon/docker-host

  database:
    image: postgres:13
    env_file: ./database/.env
    ports:
      - "5433:5432"

  database-config:
    image: postgres:13
    env_file: ./database/.env
    volumes:
      - "./database:/database"
    depends_on:
      - database
    command: /database/init.sh

  monitoring-service:
    build: ./monitoring-service
    depends_on:
      - "elastic-search"
      - "kibana"
      - "rabbitmq"
    ports:
      - "5000:5000"

  rest-api-service:
    depends_on:
      - "database"
      - "database-config"
      - "rabbitmq"
      - "web-server"
      - "docker-host"
    build: ./rest-api-service
    ports:
      - "3000:3000"

  elastic-search:
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elastic-search:9200
      ELASTICSEARCH_HOSTS: http://elastic-search:9200

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  web-server:
    image: nginx

networks:
  host_network:
    driver: host